from Esercizio1Intracorso.DoubleHashingHashMap import DoubleHashingHashMap



obj3 = DoubleHashingHashMap()

#INSERIMENTI
obj3.__setitem__("AFN",1)
obj3.__setitem__("ALL",3)
obj3.__setitem__("DZD",4)
obj3.__setitem__("EUR",5)
obj3.__setitem__("AOA",6)
obj3.__setitem__("XCD",7)
obj3.__setitem__("SAR",5)
obj3.__setitem__("ARS",5)
obj3.__setitem__("AMD",1)
obj3.__setitem__("AWG",2)
obj3.__setitem__("AUD",3)
obj3.__setitem__("BSD",4)
obj3.__setitem__("BHD",5)
obj3.__setitem__("BDT",6)
obj3.__setitem__("BDD",7)
obj3.__setitem__("BZD",5)
obj3.__setitem__("ZWL",5)
obj3.__setitem__("BMD",1)
obj3.__setitem__("BTN",3)
obj3.__setitem__("INR",4)
obj3.__setitem__("BYR",5)
obj3.__setitem__("BOB",6)
obj3.__setitem__("BOV",7)
obj3.__setitem__("BAM",5)
obj3.__setitem__("BWP",5)
obj3.__setitem__("NOK",1)
obj3.__setitem__("BRL",2)
obj3.__setitem__("BND",3)
obj3.__setitem__("BGN",4)
obj3.__setitem__("TJS",5)
obj3.__setitem__("BIF",6)
obj3.__setitem__("CVE",7)
obj3.__setitem__("KHR",5)
obj3.__setitem__("THB",5)
obj3.__setitem__("CAD",1)
obj3.__setitem__("CLF",3)
obj3.__setitem__("CLP",4)
obj3.__setitem__("CNY",5)
obj3.__setitem__("COP",6)
obj3.__setitem__("COU",7)
obj3.__setitem__("KMF",5)
obj3.__setitem__("CDF",5)
obj3.__setitem__("RON",1)
obj3.__setitem__("KRW",2)
obj3.__setitem__("KPW",3)
obj3.__setitem__("XOF",4)
obj3.__setitem__("CRC",5)
obj3.__setitem__("HRK",6)
obj3.__setitem__("CUC",7)
obj3.__setitem__("CUP",5)
obj3.__setitem__("ANG",5)
obj3.__setitem__("DKK",1)
obj3.__setitem__("TRY",3)
obj3.__setitem__("USD",4)
obj3.__setitem__("EGP",5)
obj3.__setitem__("SVC",6)
obj3.__setitem__("AED",7)
obj3.__setitem__("ERN",5)
obj3.__setitem__("ETB",5)
obj3.__setitem__("RUB",1)
obj3.__setitem__("FJD",2)
obj3.__setitem__("PHP",3)
obj3.__setitem__("XDR",4)
obj3.__setitem__("XAF",5)
obj3.__setitem__("GMD",6)
obj3.__setitem__("GEL",7)
obj3.__setitem__("GHS",5)
obj3.__setitem__("JMD",5)
obj3.__setitem__("JPY",5)
obj3.__setitem__("JOD",5)
obj3.__setitem__("UYU",2)

#CANCELLAZIONI
obj3.__delitem__("KMF")
obj3.__delitem__("CDF")
obj3.__delitem__("KRW")
obj3.__delitem__("KPW")
obj3.__delitem__("XOF")
obj3.__delitem__("CRC")
obj3.__delitem__("HRK")
obj3.__delitem__("CUC")
obj3.__delitem__("CUP")
obj3.__delitem__("ANG")
obj3.__delitem__("DKK")
obj3.__delitem__("UYU")
obj3.__delitem__("XCD")
obj3.__delitem__("USD")
obj3.__delitem__("EGP")
obj3.__delitem__("SVC")
obj3.__delitem__("AED")
obj3.__delitem__("ERN")
obj3.__delitem__("ETB")
obj3.__delitem__("RUB")
obj3.__delitem__("FJD")
obj3.__delitem__("PHP")
obj3.__delitem__("XDR")
obj3.__delitem__("XAF")
obj3.__delitem__("GMD")
obj3.__delitem__("GEL")
obj3.__delitem__("GHS")
obj3.__delitem__("JMD")
obj3.__delitem__("JPY")
obj3.__delitem__("JOD")
obj3.__delitem__("AFN")

#STAMPA
generator = obj3.__iter__()
for i in generator:
    print("Key: ", i, ";    Value: ", obj3.__getitem__(i))

#STAMPA DELLE COLLISIONI
collisions = obj3._getCollisions()
print('Collisions: ', collisions)